# Generated by Django 5.1.7 on 2025-03-24 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Expense_Summary", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="date",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="description",
        ),
        migrations.AddField(
            model_name="expense",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="expense",
            name="sub_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("transportation", "Transportation"),
                    ("education", "Education"),
                    ("utilities", "Utilities"),
                    ("entertainment", "Entertainment"),
                    ("groceries", "Groceries"),
                    ("fitness", "Fitness"),
                    ("health", "Health"),
                    ("housing", "Housing"),
                    ("shopping", "Shopping"),
                    ("fuel", "Fuel"),
                    ("dining", "Dining"),
                    ("travel", "Travel"),
                    ("personal_care", "Personal Care"),
                    ("gifts", "Gifts"),
                    ("donations", "Donations"),
                    ("sports", "Sports"),
                    ("electronics", "Electronics"),
                    ("grooming", "Grooming"),
                    ("income", "Income"),
                ],
                max_length=50,
            ),
        ),
    ]
